services:
  frontend:
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3001:3001"
    networks:
      - bot-net

networks:
  bot-net:
    name: bot-net
    external: true